"""Student progress application ports (protocols)."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from backend.v2.contexts.student_progress.domain.models import (
    LevelUpRecommendation,
    SkillCertificate,
    StudentLevelProgress,
    StudentSkillProgress,
    TestAttempt,
)


class StudentLevelProgressRepository(Protocol):
    async def save(self, progress: StudentLevelProgress) -> None: ...
    async def get_active(self, student_id: str, program_id: str) -> StudentLevelProgress | None: ...
    async def get_by_id(self, progress_id: str) -> StudentLevelProgress | None: ...
    async def complete(self, progress_id: str, completed_at: object) -> None: ...
    async def list_for_student(self, student_id: str) -> list[StudentLevelProgress]: ...


class StudentSkillProgressRepository(Protocol):
    async def save(self, skill_progress: StudentSkillProgress) -> None: ...
    async def upsert(self, skill_progress: StudentSkillProgress) -> StudentSkillProgress: ...
    async def get(self, student_id: str, skill_id: str) -> StudentSkillProgress | None: ...
    async def list_for_student_level(
        self, student_id: str, level_id: str
    ) -> list[StudentSkillProgress]: ...
    async def list_passed_for_student_level(
        self, student_id: str, level_id: str
    ) -> list[StudentSkillProgress]: ...
    async def list_for_students(
        self, student_ids: list[str], level_id: str
    ) -> list[StudentSkillProgress]: ...
    async def count_updates_by_coach(
        self, *, start_at: datetime, end_at: datetime
    ) -> list[object]: ...


class TestAttemptRepository(Protocol):
    async def save(self, attempt: TestAttempt) -> None: ...
    async def list_for_student_skill(self, student_id: str, skill_id: str) -> list[TestAttempt]: ...
    async def count_for_student_skill(self, student_id: str, skill_id: str) -> int: ...


class LevelUpRecommendationRepository(Protocol):
    async def save(self, rec: LevelUpRecommendation) -> None: ...
    async def update_status(
        self,
        rec_id: str,
        status: str,
        reviewed_by: str | None,
        reviewed_at: object | None,
        rejection_reason: str | None,
    ) -> None: ...
    async def get(self, rec_id: str) -> LevelUpRecommendation | None: ...
    async def get_active_for_student(
        self, student_id: str, program_id: str
    ) -> LevelUpRecommendation | None: ...
    async def list_pending(self) -> list[LevelUpRecommendation]: ...


class CertificateRepository(Protocol):
    async def save(self, cert: SkillCertificate) -> None: ...
    async def list_for_student(self, student_id: str) -> list[SkillCertificate]: ...


class SkillLookup(Protocol):
    """Cross-context port: reads skill/level metadata from curriculum context."""

    async def get_skill(self, skill_id: str) -> object | None: ...
    async def get_level(self, level_id: str) -> object | None: ...
    async def list_skills_for_level(self, level_id: str) -> list[object]: ...
    async def get_next_level(self, program_id: str, current_sequence: int) -> object | None: ...
