#!/usr/bin/env bash
#
# SaaS staging orchestrator. Drives a local Docker stack that approximates
# the SaaS production deployment (Wave 7 contract) for the smoke tests.
#
# Usage:
#   scripts/dev/saas_staging.sh up         # build + start backend, frontend, mongo, firebase emulator
#   scripts/dev/saas_staging.sh seed       # seed tenant + emulator user, print smoke exports
#   scripts/dev/saas_staging.sh token      # mint a fresh ID token (re-runs seed)
#   scripts/dev/saas_staging.sh smoke      # run scripts/smoke/saas_readiness_smoke.sh against the stack
#   scripts/dev/saas_staging.sh smoke --slug blno --domain blno.localhost ...
#   scripts/dev/saas_staging.sh logs <svc> # tail logs for backend|frontend|mongo|firebase-emulator
#   scripts/dev/saas_staging.sh ps         # show container status
#   scripts/dev/saas_staging.sh down       # stop containers, keep volumes
#   scripts/dev/saas_staging.sh nuke       # stop + remove volumes (fresh slate)
#
# Compose project is `saas-staging` to isolate from the default dev compose.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd)"
cd "${REPO_ROOT}"

PROJECT_NAME="saas-staging"
COMPOSE_FILES=(-f docker-compose.yml -f docker-compose.saas.yml)
COMPOSE=(docker compose -p "${PROJECT_NAME}" "${COMPOSE_FILES[@]}")

LOCAL_DIR="${REPO_ROOT}/.local"
ENV_FILE="${LOCAL_DIR}/saas-staging.env"
VENV_PYTHON="${VENV_PYTHON:-${REPO_ROOT}/backend/.venv/bin/python}"
SMOKE_SCRIPT="${REPO_ROOT}/scripts/smoke/saas_readiness_smoke.sh"
SEED_SCRIPT="${REPO_ROOT}/scripts/dev/seed_saas_staging.py"

# --- helpers ----------------------------------------------------------------

log()  { printf '\033[1;34m[saas-staging]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[saas-staging]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[saas-staging]\033[0m %s\n' "$*" >&2; exit 1; }

require_python_venv() {
  if [[ ! -x "${VENV_PYTHON}" ]]; then
    die "backend/.venv not found. Create it with:
  python3 -m venv backend/.venv
  backend/.venv/bin/pip install -r backend/requirements.txt"
  fi
}

# Generate random hex secret without echoing to a log file.
random_hex() { LC_ALL=C openssl rand -hex "${1:-32}"; }

# Generate a strong random password (only printable, no quotes/backslash).
random_password() {
  LC_ALL=C openssl rand -base64 36 | tr -d '\n=+/' | cut -c1-28
}

ensure_env_file() {
  if [[ -f "${ENV_FILE}" ]]; then
    return 0
  fi
  log "Generating fresh local SaaS staging secrets at ${ENV_FILE}"
  mkdir -p "${LOCAL_DIR}"
  umask 077
  {
    printf '# Auto-generated by scripts/dev/saas_staging.sh\n'
    printf '# Local Docker SaaS staging stack only. Never commit.\n'
    printf 'JWT_SECRET=%s\n' "$(random_hex 32)"
    printf 'ADMIN_PASSWORD=%s\n' "$(random_password)"
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
}

cmd_up() {
  ensure_env_file
  log "Building and starting stack (project=${PROJECT_NAME})..."
  "${COMPOSE[@]}" up -d --build
  log "Stack is up. Waiting for backend health..."

  # Wait up to 90s for the backend to respond to /api/v2/healthz.
  local deadline=$(( $(date +%s) + 90 ))
  while (( $(date +%s) < deadline )); do
    if curl -fsS http://127.0.0.1:8001/api/v2/healthz >/dev/null 2>&1; then
      log "Backend is healthy. Next step: scripts/dev/saas_staging.sh seed"
      return 0
    fi
    sleep 2
  done
  warn "Backend did not respond on http://127.0.0.1:8001/api/v2/healthz within 90s."
  warn "Run: scripts/dev/saas_staging.sh logs backend"
  exit 1
}

cmd_seed() {
  require_python_venv
  log "Seeding tenant + Firebase emulator user..."
  "${VENV_PYTHON}" "${SEED_SCRIPT}" "$@"
}

cmd_token() {
  # Same as seed (idempotent): re-runs and prints a fresh ID token.
  cmd_seed "$@"
}

cmd_smoke() {
  require_python_venv
  [[ -x "${SMOKE_SCRIPT}" ]] || die "Smoke script not found or not executable: ${SMOKE_SCRIPT}"

  log "Generating fresh smoke env from seed..."
  local seed_json
  seed_json="$("${VENV_PYTHON}" "${SEED_SCRIPT}" --json "$@")"

  local api_url frontend_url tenant_frontend_url tenant_host hdr_name hdr_val id_token
  api_url="$(printf '%s' "${seed_json}"      | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["api_url"])')"
  frontend_url="$(printf '%s' "${seed_json}" | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["frontend_url"])')"
  tenant_frontend_url="$(printf '%s' "${seed_json}" | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["tenant_frontend_url"])')"
  tenant_host="$(printf '%s' "${seed_json}"  | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["unknown_host_for_smoke"])')"
  hdr_name="$(printf '%s' "${seed_json}"     | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["internal_tenant_header_name"])')"
  hdr_val="$(printf '%s' "${seed_json}"      | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["academy_id"])')"
  id_token="$(printf '%s' "${seed_json}"     | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["id_token"])')"

  log "Running SaaS readiness smoke against ${api_url}..."
  API_URL="${api_url}" \
  FRONTEND_URL="${frontend_url}" \
  TENANT_FRONTEND_URL="${tenant_frontend_url}" \
  TENANT_HOST="${tenant_host}" \
  INTERNAL_TENANT_HEADER_NAME="${hdr_name}" \
  INTERNAL_TENANT_HEADER_VALUE="${hdr_val}" \
  AUTH_TOKEN="${id_token}" \
    "${SMOKE_SCRIPT}"
}

cmd_logs() {
  local service="${1:-backend}"
  shift || true
  "${COMPOSE[@]}" logs -f --tail=200 "${service}" "$@"
}

cmd_ps() {
  "${COMPOSE[@]}" ps
}

cmd_down() {
  log "Stopping stack (keeping volumes)..."
  "${COMPOSE[@]}" down
}

cmd_nuke() {
  warn "This will remove all SaaS-staging containers AND volumes (Mongo data, emulator state)."
  read -r -p "Type 'nuke' to confirm: " confirm
  [[ "${confirm}" == "nuke" ]] || die "Aborted."
  "${COMPOSE[@]}" down -v
  rm -f "${ENV_FILE}" || true
  rm -f "${LOCAL_DIR}/saas-staging-credentials.json" || true
  log "Nuked. Run 'up' to rebuild from a clean slate."
}

usage() {
  sed -n '3,18p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

main() {
  local cmd="${1:-}"
  shift || true
  case "${cmd}" in
    up)     cmd_up "$@" ;;
    seed)   cmd_seed "$@" ;;
    token)  cmd_token "$@" ;;
    smoke)  cmd_smoke "$@" ;;
    logs)   cmd_logs "$@" ;;
    ps)     cmd_ps "$@" ;;
    down)   cmd_down "$@" ;;
    nuke)   cmd_nuke "$@" ;;
    ""|-h|--help|help) usage ;;
    *) usage; die "Unknown command: ${cmd}" ;;
  esac
}

main "$@"
