#!/usr/bin/env bash
#
# Phase B: Cloudflare quick-tunnel overlay for SaaS staging.
#
# Usage:
#   scripts/dev/saas_tunnel.sh up      # start cloudflared sidecars, discover URLs, patch backend CORS, restart backend
#   scripts/dev/saas_tunnel.sh urls    # print the current tunnel URLs (backend + frontend)
#   scripts/dev/saas_tunnel.sh smoke   # run the SaaS smoke against the tunnel URLs
#   scripts/dev/saas_tunnel.sh down    # stop cloudflared sidecars only (leaves base SaaS stack up)
#
# Requires that `scripts/dev/saas_staging.sh up` has already been run.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd)"
cd "${REPO_ROOT}"

PROJECT_NAME="saas-staging"
COMPOSE=(
  docker compose
  -p "${PROJECT_NAME}"
  -f docker-compose.yml
  -f docker-compose.saas.yml
  -f docker-compose.tunnel.yml
)

VENV_PYTHON="${REPO_ROOT}/backend/.venv/bin/python"
SMOKE_SCRIPT="${REPO_ROOT}/scripts/smoke/saas_readiness_smoke.sh"
SEED_SCRIPT="${REPO_ROOT}/scripts/dev/seed_saas_staging.py"
TUNNEL_URLS_FILE="${REPO_ROOT}/.local/saas-tunnel-urls.env"

log()  { printf '\033[1;34m[saas-tunnel]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[saas-tunnel]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[saas-tunnel]\033[0m %s\n' "$*" >&2; exit 1; }

# Discover the public quick-tunnel URL from cloudflared's logs.
# We tail until the first `https://*.trycloudflare.com` line appears, or
# we hit the timeout. Quick tunnels print the URL in a `+--...+` banner.
discover_tunnel_url() {
  local service="$1"
  local timeout_s="${2:-90}"
  local deadline=$(( $(date +%s) + timeout_s ))
  local url=""

  while (( $(date +%s) < deadline )); do
    url="$(
      "${COMPOSE[@]}" logs --no-color --no-log-prefix "${service}" 2>/dev/null \
        | grep -Eo 'https://[a-z0-9-]+\.trycloudflare\.com' \
        | tail -n 1 || true
    )"
    if [[ -n "${url}" ]]; then
      printf '%s\n' "${url}"
      return 0
    fi
    sleep 2
  done

  warn "Timed out waiting for ${service} to print its trycloudflare.com URL."
  warn "Tail the logs:  ${COMPOSE[*]} logs ${service}"
  return 1
}

cmd_up() {
  log "Starting cloudflared sidecars..."
  "${COMPOSE[@]}" up -d cloudflared-backend cloudflared-frontend

  log "Discovering backend tunnel URL (this can take 10-30s)..."
  local backend_url frontend_url
  backend_url="$(discover_tunnel_url cloudflared-backend 90)"

  log "Discovering frontend tunnel URL..."
  frontend_url="$(discover_tunnel_url cloudflared-frontend 90)"

  log "Tunnels up:"
  log "  backend  -> ${backend_url}"
  log "  frontend -> ${frontend_url}"

  mkdir -p "$(dirname "${TUNNEL_URLS_FILE}")"
  {
    printf '# Auto-generated by scripts/dev/saas_tunnel.sh\n'
    printf 'SAAS_TUNNEL_BACKEND_URL=%s\n' "${backend_url}"
    printf 'SAAS_TUNNEL_FRONTEND_URL=%s\n' "${frontend_url}"
  } > "${TUNNEL_URLS_FILE}"
  chmod 600 "${TUNNEL_URLS_FILE}"

  log "Patching backend CORS_ORIGINS + FRONTEND_URL to include the tunnel URL and restarting backend..."
  CORS_EXTRA="${frontend_url}" FRONTEND_URL_NEW="${frontend_url}" \
    "${COMPOSE[@]}" up -d --no-deps \
      --build=false \
      --remove-orphans=false \
      backend >/dev/null 2>&1 || true

  # The cleanest way to inject an env var into the running backend is to
  # exec a new process with the updated env. Compose can't merge envs on
  # the fly, so we restart with `run -e` would lose state. Instead we use
  # `exec` to call our reload helper if present, else `restart`.
  "${COMPOSE[@]}" exec -e CORS_ORIGINS="http://localhost:3000,http://acme.localhost:3000,http://127.0.0.1:3000,${frontend_url}" \
    -e FRONTEND_URL="${frontend_url}" \
    -d backend sh -c 'pkill -HUP -f uvicorn || true' 2>/dev/null || true

  # If HUP doesn't reload (uvicorn without --reload), do a hard service
  # restart with overrides via environment passed at recreate time. We
  # emit a docker compose override at runtime for the env vars.
  cat > "${REPO_ROOT}/.local/saas-tunnel-cors.yml" <<EOF
services:
  backend:
    environment:
      CORS_ORIGINS: "http://localhost:3000,http://acme.localhost:3000,http://127.0.0.1:3000,${frontend_url}"
      FRONTEND_URL: "${frontend_url}"
EOF
  docker compose -p "${PROJECT_NAME}" \
    -f docker-compose.yml \
    -f docker-compose.saas.yml \
    -f docker-compose.tunnel.yml \
    -f "${REPO_ROOT}/.local/saas-tunnel-cors.yml" \
    up -d --no-build backend

  log "Backend restarted with extended CORS. Run: scripts/dev/saas_tunnel.sh smoke"
}

cmd_urls() {
  if [[ ! -f "${TUNNEL_URLS_FILE}" ]]; then
    die "No tunnel URLs recorded yet. Run 'up' first."
  fi
  cat "${TUNNEL_URLS_FILE}"
}

cmd_smoke() {
  [[ -x "${VENV_PYTHON}" ]] || die "backend/.venv not found"
  [[ -x "${SMOKE_SCRIPT}" ]] || die "Smoke script missing: ${SMOKE_SCRIPT}"
  [[ -f "${TUNNEL_URLS_FILE}" ]] || die "No tunnel URLs recorded. Run 'up' first."

  # shellcheck disable=SC1090
  source "${TUNNEL_URLS_FILE}"

  log "Seeding fresh ID token..."
  local seed_json
  seed_json="$("${VENV_PYTHON}" "${SEED_SCRIPT}" --json)"

  local academy_id id_token
  academy_id="$(printf '%s' "${seed_json}" | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["academy_id"])')"
  id_token="$(printf '%s' "${seed_json}"   | "${VENV_PYTHON}" -c 'import json,sys;print(json.load(sys.stdin)["id_token"])')"

  log "Running SaaS readiness smoke against tunnel URLs:"
  log "  API_URL=${SAAS_TUNNEL_BACKEND_URL}"
  log "  FRONTEND_URL=${SAAS_TUNNEL_FRONTEND_URL}"

  API_URL="${SAAS_TUNNEL_BACKEND_URL}" \
  FRONTEND_URL="${SAAS_TUNNEL_FRONTEND_URL}" \
  TENANT_HOST="tenant-smoke.localhost" \
  INTERNAL_TENANT_HEADER_NAME="x-internal-tenant-id" \
  INTERNAL_TENANT_HEADER_VALUE="${academy_id}" \
  AUTH_TOKEN="${id_token}" \
    "${SMOKE_SCRIPT}"
}

cmd_down() {
  log "Stopping cloudflared sidecars (base SaaS stack stays up)..."
  "${COMPOSE[@]}" stop cloudflared-backend cloudflared-frontend
  "${COMPOSE[@]}" rm -f cloudflared-backend cloudflared-frontend
  rm -f "${TUNNEL_URLS_FILE}"
  rm -f "${REPO_ROOT}/.local/saas-tunnel-cors.yml"
  log "Tunnels down. Backend retains the CORS extension from the last 'up' — restart base stack to fully revert."
}

usage() {
  sed -n '3,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

main() {
  local cmd="${1:-}"
  shift || true
  case "${cmd}" in
    up)    cmd_up ;;
    urls)  cmd_urls ;;
    smoke) cmd_smoke ;;
    down)  cmd_down ;;
    ""|-h|--help|help) usage ;;
    *) usage; die "Unknown command: ${cmd}" ;;
  esac
}

main "$@"
