#!/usr/bin/env python3
"""Seed a SaaS staging tenant + Firebase emulator user.

Run from the host (uses backend/.venv) once the SaaS staging stack is up:

    backend/.venv/bin/python scripts/dev/seed_saas_staging.py

What this creates:
  - Mongo DB `academy_manager_saas_staging`:
      * `academies`             : tenant "acme" with primary_domain acme.localhost
      * `users`                 : owner user, linked to Firebase emulator UID
      * `academy_memberships`   : active admin membership for owner
      * `academy_settings`      : default settings
      * `platform_roles`        : owner is also platform_admin (for /platform routes)
  - Firebase Auth Emulator (project academy-courtmastr):
      * user `admin@acme.localhost` with password `SaaS-Stage-Pass-1!`

Idempotent: re-running upserts; safe across reboots.

Prints a fresh Firebase ID token + the env exports needed for the smoke.

This script is for **local Docker SaaS staging only**. Never run it against
production Mongo or a real Firebase project.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import secrets
import string
import sys
import time
from pathlib import Path
from typing import Any

import httpx
from pymongo import MongoClient, ReturnDocument
from pymongo.errors import PyMongoError


# --- Defaults & runtime config ----------------------------------------------
#
# SECURITY NOTE:
# This script creates an account in the **Firebase Auth Emulator** and a
# **local Docker Mongo**. No real credentials live in this file:
#
#  - The owner password is generated randomly on first run and persisted to
#    `.local/saas-staging-credentials.json` (gitignored). Subsequent runs
#    reuse it. Override via SAAS_STAGING_OWNER_PASSWORD env if you need a
#    specific value.
#  - The "API key" passed to the emulator is not a credential — the Firebase
#    Auth Emulator accepts any non-empty string and does not validate it.
#    See https://firebase.google.com/docs/emulator-suite/connect_auth.
#
# `_assert_local()` refuses to run against any non-loopback Mongo or
# emulator URL, so this script cannot accidentally hit real infrastructure.

DEFAULT_MONGO_URL = "mongodb://127.0.0.1:27017"
DEFAULT_DB_NAME = "academy_manager_saas_staging"
DEFAULT_EMULATOR_URL = "http://127.0.0.1:9099"
DEFAULT_PROJECT_ID = "academy-courtmastr"
DEFAULT_TENANT_SLUG = "acme"
DEFAULT_TENANT_DOMAIN = "acme.localhost"
# Email must pass pydantic EmailStr (rejects reserved TLDs like .localhost, .test).
# We use a real-format synthetic address; DNS is never resolved.
DEFAULT_OWNER_EMAIL = os.environ.get("SAAS_STAGING_OWNER_EMAIL", "admin@acme-saas-staging.dev")
DEFAULT_OWNER_NAME = "Acme Admin"
DEFAULT_TENANT_DISPLAY_NAME = "Acme Badminton Academy"

# Where we persist the locally-generated emulator password.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
LOCAL_CREDS_DIR = PROJECT_ROOT / ".local"
LOCAL_CREDS_FILE = LOCAL_CREDS_DIR / "saas-staging-credentials.json"

# The emulator does not validate this; any non-empty string is accepted.
# Computed (not literal) to make the lack-of-secret nature obvious.
EMULATOR_API_KEY = "emu-" + DEFAULT_PROJECT_ID


def _generate_password() -> str:
    """Generate a fresh emulator-only password.

    Uses ``secrets`` for entropy. Mixes a-z, A-Z, 0-9, and a small punctuation
    set so the result satisfies the strictest Firebase Auth password rules.
    """

    alphabet = string.ascii_letters + string.digits + "!@#$%^&*-_"
    return "".join(secrets.choice(alphabet) for _ in range(28))


def _credentials_note() -> str:
    return (
        "Local Firebase Auth Emulator credentials only. "
        "Auto-generated by scripts/dev/seed_saas_staging.py. "
        "Do not reuse for real Firebase projects."
    )


def _load_or_create_owner_password(owner_email: str) -> str:
    """Return the emulator owner password, generating + persisting if absent.

    Resolution order:
      1. SAAS_STAGING_OWNER_PASSWORD env var (explicit override)
      2. `.local/saas-staging-credentials.json` for this owner email
      3. Generate a fresh value, persist to (2), return it.
    """

    env_value = os.environ.get("SAAS_STAGING_OWNER_PASSWORD")
    if env_value:
        return env_value

    normalized_email = owner_email.strip().lower()
    data: dict[str, Any] = {}
    if LOCAL_CREDS_FILE.exists():
        try:
            loaded = json.loads(LOCAL_CREDS_FILE.read_text())
            if isinstance(loaded, dict):
                data = loaded
        except (OSError, ValueError):
            data = {}

    owners = data.get("owners")
    if not isinstance(owners, dict):
        owners = {}

    # Backward compatibility for the original single-owner credential file.
    legacy_email = data.get("owner_email")
    legacy_password = data.get("owner_password")
    if isinstance(legacy_email, str) and isinstance(legacy_password, str):
        legacy_key = legacy_email.strip().lower()
        owners.setdefault(
            legacy_key,
            {"owner_email": legacy_email, "owner_password": legacy_password},
        )

    existing = owners.get(normalized_email)
    if isinstance(existing, dict):
        value = existing.get("owner_password")
        if isinstance(value, str) and value:
            return value

    generated = _generate_password()
    LOCAL_CREDS_DIR.mkdir(parents=True, exist_ok=True)
    owners[normalized_email] = {
        "owner_email": owner_email,
        "owner_password": generated,
    }
    LOCAL_CREDS_FILE.write_text(
        json.dumps(
            {
                "owners": owners,
                "note": _credentials_note(),
            },
            indent=2,
        )
    )
    try:
        LOCAL_CREDS_FILE.chmod(0o600)
    except OSError:
        pass
    return generated


def _assert_local(*, mongo_url: str, emulator_url: str) -> None:
    """Refuse to run against anything but loopback / docker-local hosts.

    Guards against accidentally pointing this seed at real Mongo or a real
    Firebase project. The defaults are local-only; this enforces that even
    when overridden via env or CLI.
    """

    import urllib.parse as _urlparse

    allowed_hosts = {"127.0.0.1", "localhost", "::1", "mongo", "firebase-emulator"}

    def _host(url: str) -> str:
        # MongoClient accepts mongodb:// URLs; urlparse handles them.
        parsed = _urlparse.urlparse(url)
        host = parsed.hostname or ""
        return host.lower()

    for label, url in (("mongo", mongo_url), ("emulator", emulator_url)):
        host = _host(url)
        if host not in allowed_hosts:
            raise SystemExit(
                f"REFUSING: {label} URL host {host!r} is not in the local allow-list "
                f"{sorted(allowed_hosts)}. This script seeds emulator-only test "
                f"credentials and must never run against real infrastructure."
            )


# --- Helpers ----------------------------------------------------------------


def now() -> _dt.datetime:
    return _dt.datetime.now(_dt.UTC)


def wait_for_emulator(emulator_url: str, *, timeout_s: int = 60) -> None:
    """Block until the Firebase Auth Emulator responds, or raise."""
    deadline = time.monotonic() + timeout_s
    last_err: Exception | None = None
    while time.monotonic() < deadline:
        try:
            resp = httpx.get(f"{emulator_url}/", timeout=2.0)
            if resp.status_code < 500:
                return
        except (httpx.HTTPError, OSError) as err:
            last_err = err
        time.sleep(1)
    raise RuntimeError(
        f"Firebase emulator at {emulator_url} did not become ready within "
        f"{timeout_s}s (last error: {last_err!r})"
    )


def wait_for_mongo(client: MongoClient[Any], *, timeout_s: int = 30) -> None:
    deadline = time.monotonic() + timeout_s
    last_err: Exception | None = None
    while time.monotonic() < deadline:
        try:
            client.admin.command("ping")
            return
        except PyMongoError as err:
            last_err = err
        time.sleep(1)
    raise RuntimeError(f"Mongo did not become ready within {timeout_s}s ({last_err!r})")


def upsert_emulator_user(
    *, emulator_url: str, api_key: str, email: str, password: str, display_name: str
) -> str:
    """Create or look up a Firebase Auth emulator user. Returns the UID."""

    # First try signUp; the emulator returns EMAIL_EXISTS if already present.
    signup_url = (
        f"{emulator_url}/identitytoolkit.googleapis.com/v1/accounts:signUp?key={api_key}"
    )
    signup_payload = {
        "email": email,
        "password": password,
        "displayName": display_name,
        "returnSecureToken": True,
    }
    resp = httpx.post(signup_url, json=signup_payload, timeout=5.0)
    if resp.status_code == 200:
        body = resp.json()
        uid = str(body["localId"])
        _mark_emulator_user_verified(emulator_url=emulator_url, uid=uid)
        return uid

    # Already exists → look it up via project-level lookup endpoint.
    if resp.status_code == 400 and "EMAIL_EXISTS" in resp.text:
        lookup_url = (
            f"{emulator_url}/identitytoolkit.googleapis.com/v1/accounts:lookup?key={api_key}"
        )
        # signInWithPassword is the easiest way to get back the localId.
        signin_url = (
            f"{emulator_url}/identitytoolkit.googleapis.com/v1/"
            f"accounts:signInWithPassword?key={api_key}"
        )
        signin = httpx.post(
            signin_url,
            json={"email": email, "password": password, "returnSecureToken": True},
            timeout=5.0,
        )
        if signin.status_code == 400:
            return reset_emulator_user_password(
                emulator_url=emulator_url,
                email=email,
                password=password,
                display_name=display_name,
            )
        signin.raise_for_status()
        token = signin.json()["idToken"]
        lookup = httpx.post(lookup_url, json={"idToken": token}, timeout=5.0)
        lookup.raise_for_status()
        users = lookup.json().get("users") or []
        if not users:
            raise RuntimeError("Emulator reported EMAIL_EXISTS but lookup returned no users")
        uid = str(users[0]["localId"])
        _mark_emulator_user_verified(emulator_url=emulator_url, uid=uid)
        return uid

    raise RuntimeError(
        f"Failed to create emulator user (status={resp.status_code}): {resp.text}"
    )


def reset_emulator_user_password(
    *,
    emulator_url: str,
    email: str,
    password: str,
    display_name: str,
) -> str:
    """Reset an existing Firebase Auth Emulator user's password.

    This is deliberately emulator-only. `_assert_local()` runs before seeding,
    and the Admin SDK call points at `FIREBASE_AUTH_EMULATOR_HOST`, not a real
    Firebase project.
    """

    import urllib.parse as _urlparse

    import firebase_admin
    from firebase_admin import auth

    parsed = _urlparse.urlparse(emulator_url)
    emulator_host = parsed.netloc or parsed.path
    if not emulator_host:
        raise RuntimeError(f"Invalid Firebase emulator URL: {emulator_url}")

    previous_host = os.environ.get("FIREBASE_AUTH_EMULATOR_HOST")
    os.environ["FIREBASE_AUTH_EMULATOR_HOST"] = emulator_host
    app_name = f"saas-staging-seed-{DEFAULT_PROJECT_ID}"
    try:
        try:
            app = firebase_admin.get_app(app_name)
        except ValueError:
            app = firebase_admin.initialize_app(
                options={"projectId": DEFAULT_PROJECT_ID},
                name=app_name,
            )
        user = auth.get_user_by_email(email, app=app)
        auth.update_user(
            user.uid,
            password=password,
            display_name=display_name,
            email_verified=True,
            app=app,
        )
        return str(user.uid)
    finally:
        if previous_host is None:
            os.environ.pop("FIREBASE_AUTH_EMULATOR_HOST", None)
        else:
            os.environ["FIREBASE_AUTH_EMULATOR_HOST"] = previous_host


def _mark_emulator_user_verified(*, emulator_url: str, uid: str) -> None:
    """Mark a Firebase Auth emulator user verified via the Admin SDK."""

    import urllib.parse as _urlparse

    import firebase_admin
    from firebase_admin import auth

    parsed = _urlparse.urlparse(emulator_url)
    emulator_host = parsed.netloc or parsed.path
    if not emulator_host:
        raise RuntimeError(f"Invalid Firebase emulator URL: {emulator_url}")

    previous_host = os.environ.get("FIREBASE_AUTH_EMULATOR_HOST")
    os.environ["FIREBASE_AUTH_EMULATOR_HOST"] = emulator_host
    app_name = f"saas-staging-seed-{DEFAULT_PROJECT_ID}"
    try:
        try:
            app = firebase_admin.get_app(app_name)
        except ValueError:
            app = firebase_admin.initialize_app(
                options={"projectId": DEFAULT_PROJECT_ID},
                name=app_name,
            )
        auth.update_user(uid, email_verified=True, app=app)
    finally:
        if previous_host is None:
            os.environ.pop("FIREBASE_AUTH_EMULATOR_HOST", None)
        else:
            os.environ["FIREBASE_AUTH_EMULATOR_HOST"] = previous_host


def mint_id_token(*, emulator_url: str, api_key: str, email: str, password: str) -> str:
    url = (
        f"{emulator_url}/identitytoolkit.googleapis.com/v1/"
        f"accounts:signInWithPassword?key={api_key}"
    )
    resp = httpx.post(
        url,
        json={"email": email, "password": password, "returnSecureToken": True},
        timeout=5.0,
    )
    resp.raise_for_status()
    return str(resp.json()["idToken"])


def upsert_tenant_records(
    *,
    db: Any,
    slug: str,
    primary_domain: str,
    display_name: str,
    owner_email: str,
    owner_display_name: str,
    firebase_uid: str,
) -> dict[str, Any]:
    """Upsert academy + owner user + membership + settings + platform_role.

    Returns identifiers we want to surface back to the operator.
    """

    ts = now()
    normalized_email = owner_email.strip().lower()

    # --- Academy: keyed by slug, also enforce domain uniqueness on read.
    # Mongo refuses overlapping paths between $setOnInsert and $set — keep
    # immutable-on-insert fields here and idempotent updates in $set only.
    academy_doc_set_on_insert: dict[str, Any] = {
        "academy_id": f"acad_{slug}",
        "slug": slug,
        "display_name": display_name,
        "timezone": "America/New_York",
        "status": "active",
        "owner_email": owner_email,
        "created_at": ts,
    }
    academy = db.academies.find_one_and_update(
        {"slug": slug},
        {
            "$setOnInsert": academy_doc_set_on_insert,
            "$set": {"updated_at": ts, "primary_domain": primary_domain},
        },
        upsert=True,
        return_document=ReturnDocument.AFTER,
    )
    academy_id = str(academy["academy_id"])

    # --- Global user keyed by email (the unique index in this collection).
    # All identity fields go into $set so partial docs from earlier failed
    # runs get backfilled rather than blocking on the unique constraint.
    user = db.users.find_one_and_update(
        {"email": owner_email},
        {
            "$setOnInsert": {
                "created_at": ts,
            },
            "$set": {
                "updated_at": ts,
                "user_id": firebase_uid,
                "normalized_email": normalized_email,
                "display_name": owner_display_name,
                "global_status": "active",
                "is_active": True,
                "roles": ["admin"],
                "role": "admin",
                "academy_id": academy_id,
                "firebase_uid": firebase_uid,
                "auth_uid": firebase_uid,
                "auth_provider": "firebase",
            },
        },
        upsert=True,
        return_document=ReturnDocument.AFTER,
    )
    user_id = str(user["user_id"])

    # --- Owner membership (active admin) keyed by (academy_id, user_id).
    membership = db.academy_memberships.find_one_and_update(
        {"academy_id": academy_id, "user_id": user_id},
        {
            "$setOnInsert": {
                "membership_id": f"mem_{slug}_{user_id[:8]}",
                "academy_id": academy_id,
                "user_id": user_id,
                "accepted_at": ts,
                "created_at": ts,
            },
            "$set": {"updated_at": ts, "roles": ["admin"], "status": "active"},
        },
        upsert=True,
        return_document=ReturnDocument.AFTER,
    )

    # --- Academy settings (so admin dashboards don't 404 on settings reads).
    db.academy_settings.find_one_and_update(
        {"academy_id": academy_id},
        {
            "$setOnInsert": {
                "settings_id": f"set_{slug}",
                "academy_id": academy_id,
                "display_name": display_name,
                "timezone": "America/New_York",
                "locale": "en-US",
                "created_at": ts,
            },
            "$set": {"updated_at": ts},
        },
        upsert=True,
    )

    # --- Platform role: make this user a platform_admin too, so /platform/*
    #     routes (including bootstrap) work in staging.
    db.platform_roles.find_one_and_update(
        {"user_id": user_id, "role": "platform_admin"},
        {
            "$setOnInsert": {
                "platform_role_id": f"prole_{user_id[:8]}",
                "granted_at": ts,
                "created_at": ts,
            },
            "$set": {"updated_at": ts, "status": "active"},
        },
        upsert=True,
    )

    return {
        "academy_id": academy_id,
        "slug": str(academy["slug"]),
        "primary_domain": str(academy["primary_domain"]),
        "user_id": user_id,
        "membership_id": str(membership["membership_id"]),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Seed SaaS staging Mongo tenant + Firebase emulator user."
    )
    parser.add_argument(
        "--mongo-url",
        default=os.environ.get("SAAS_STAGING_MONGO_URL", DEFAULT_MONGO_URL),
        help="Mongo connection URL (default: %(default)s)",
    )
    parser.add_argument(
        "--db-name",
        default=os.environ.get("SAAS_STAGING_DB_NAME", DEFAULT_DB_NAME),
        help="Mongo database (default: %(default)s)",
    )
    parser.add_argument(
        "--emulator-url",
        default=os.environ.get("SAAS_STAGING_EMULATOR_URL", DEFAULT_EMULATOR_URL),
        help="Firebase Auth emulator base URL (default: %(default)s)",
    )
    parser.add_argument("--slug", default=DEFAULT_TENANT_SLUG)
    parser.add_argument("--domain", default=DEFAULT_TENANT_DOMAIN)
    parser.add_argument("--display-name", default=DEFAULT_TENANT_DISPLAY_NAME)
    parser.add_argument("--owner-email", default=DEFAULT_OWNER_EMAIL)
    parser.add_argument(
        "--owner-password",
        default=None,
        help=(
            "Owner password for the emulator user. Defaults to value in "
            ".local/saas-staging-credentials.json (auto-generated on first run) "
            "or SAAS_STAGING_OWNER_PASSWORD env."
        ),
    )
    parser.add_argument("--owner-name", default=DEFAULT_OWNER_NAME)
    parser.add_argument(
        "--print-exports",
        action="store_true",
        help="Print smoke env exports (default behaviour).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON instead of human output.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    _assert_local(mongo_url=args.mongo_url, emulator_url=args.emulator_url)

    owner_password = args.owner_password or _load_or_create_owner_password(args.owner_email)

    print(f"[seed] Waiting for Firebase emulator at {args.emulator_url}...", file=sys.stderr)
    wait_for_emulator(args.emulator_url)

    print(f"[seed] Connecting to Mongo at {args.mongo_url} (db={args.db_name})...", file=sys.stderr)
    client: MongoClient[Any] = MongoClient(args.mongo_url, serverSelectionTimeoutMS=5_000)
    wait_for_mongo(client)
    db = client[args.db_name]

    print(f"[seed] Upserting Firebase emulator user {args.owner_email}...", file=sys.stderr)
    firebase_uid = upsert_emulator_user(
        emulator_url=args.emulator_url,
        api_key=EMULATOR_API_KEY,
        email=args.owner_email,
        password=owner_password,
        display_name=args.owner_name,
    )

    print(f"[seed] Upserting tenant records for slug={args.slug}...", file=sys.stderr)
    tenant = upsert_tenant_records(
        db=db,
        slug=args.slug,
        primary_domain=args.domain,
        display_name=args.display_name,
        owner_email=args.owner_email,
        owner_display_name=args.owner_name,
        firebase_uid=firebase_uid,
    )

    print("[seed] Minting fresh ID token for smoke...", file=sys.stderr)
    id_token = mint_id_token(
        emulator_url=args.emulator_url,
        api_key=EMULATOR_API_KEY,
        email=args.owner_email,
        password=owner_password,
    )

    result = {
        **tenant,
        "firebase_uid": firebase_uid,
        "owner_email": args.owner_email,
        "owner_password_file": str(LOCAL_CREDS_FILE),
        "id_token": id_token,
        "api_url": "http://127.0.0.1:8001",
        "frontend_url": "http://localhost:3000",
        "tenant_frontend_url": f"http://{args.domain}:3000",
        "tenant_host": f"{args.domain}",
        "unknown_host_for_smoke": "tenant-smoke.localhost",
        "internal_tenant_header_name": "x-internal-tenant-id",
    }

    if args.json:
        print(json.dumps(result, indent=2, default=str))
        return 0

    print("\n=== SaaS staging seed complete ===")
    print(f"  Academy:         {result['academy_id']}  (slug={result['slug']})")
    print(f"  Primary domain:  {result['primary_domain']}")
    print(f"  Owner user:      {result['user_id']}  ({result['owner_email']})")
    print(f"  Firebase UID:    {result['firebase_uid']}")
    print(f"  Owner password:  (in {result['owner_password_file']})")
    print()
    print("Smoke env exports (paste into a shell):")
    print()
    print(f"  export API_URL='{result['api_url']}'")
    print(f"  export FRONTEND_URL='{result['frontend_url']}'")
    print(f"  export TENANT_FRONTEND_URL='{result['tenant_frontend_url']}'")
    print(f"  export TENANT_HOST='{result['unknown_host_for_smoke']}'")
    print(f"  export INTERNAL_TENANT_HEADER_NAME='{result['internal_tenant_header_name']}'")
    print(f"  export INTERNAL_TENANT_HEADER_VALUE='{result['academy_id']}'")
    print(
        "  # Internal tenant header is secret-gated (issue #519):"
        " read V2_PROXY_SHARED_SECRET from .local/saas-staging.env"
    )
    print("  export PROXY_AUTH_VALUE='<V2_PROXY_SHARED_SECRET from .local/saas-staging.env>'")
    print(f"  export AUTH_TOKEN='{result['id_token']}'")
    print()
    print("Then run:  scripts/smoke/saas_readiness_smoke.sh")
    print()
    print("Note: the ID token expires in 1 hour. Re-run this script to mint a fresh one.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
