"""Curriculum application ports (protocols)."""

from __future__ import annotations

from typing import Protocol

from backend.v2.contexts.curriculum.domain.models import (
    ExternalLessonReference,
    FullPathway,
    Level,
    Program,
    Skill,
    SkillCriterion,
)


class ProgramRepository(Protocol):
    async def save(self, program: Program) -> None: ...
    async def get(self, program_id: str) -> Program | None: ...
    async def list_active(self) -> list[Program]: ...


class LevelRepository(Protocol):
    async def save(self, level: Level) -> None: ...
    async def update(self, level: Level) -> None: ...
    async def get(self, level_id: str) -> Level | None: ...
    async def list_for_program(self, program_id: str) -> list[Level]: ...


class SkillRepository(Protocol):
    async def save(self, skill: Skill) -> None: ...
    async def update(self, skill: Skill) -> None: ...
    async def get(self, skill_id: str) -> Skill | None: ...
    async def list_for_level(self, level_id: str) -> list[Skill]: ...
    async def list_for_program(self, program_id: str) -> list[Skill]: ...


class CriterionRepository(Protocol):
    async def save(self, criterion: SkillCriterion) -> None: ...
    async def list_for_skill(self, skill_id: str) -> list[SkillCriterion]: ...


class ExternalRefRepository(Protocol):
    async def save(self, ref: ExternalLessonReference) -> None: ...
    async def list_for_skill(self, skill_id: str) -> list[ExternalLessonReference]: ...


class PathwayQuery(Protocol):
    async def get_full_pathway(self, program_id: str) -> FullPathway | None: ...
